import{describe,expect,it}from"vitest";import{initialPathAState,reducePathA,type PathAEvent}from"../../src/lib/pairing/path-a-state-machine";
const room={schema:"focusa.cockpit_pairing_room.v1",room_id:"room_1",nonce:"nonce_1",client_type:"cockpit",daemon_url:"https://focusa.example",status:"created",created_at:"2026-08-03T00:00:00Z",expires_at:"2026-08-03T00:05:00Z",bridge_owner:"cockpit"}as const;
const advance=(events:PathAEvent[])=>events.reduce(reducePathA,initialPathAState());
describe("Path A state machine",()=>{
 it("follows the sole success path",()=>{const state=advance([{type:"START"},{type:"ROOM_CREATED",room},{type:"STATUS",status:"awaiting_vps"},{type:"STATUS",status:"completed"},{type:"COMPLETION_VALIDATED"},{type:"CREDENTIAL_PERSISTED"},{type:"PROFILE_VERIFIED"}]);expect(state).toMatchObject({phase:"completed",attempt:1,cleanup_required:true});});
 it.each(["awaiting_operator","awaiting_vps","completing","persisting","verifying"] as const)("cancels from %s with cleanup",phase=>{let state=advance([{type:"START"},{type:"ROOM_CREATED",room}]);const path:PathAEvent[]=[{type:"STATUS",status:"awaiting_vps"},{type:"STATUS",status:"completed"},{type:"COMPLETION_VALIDATED"},{type:"CREDENTIAL_PERSISTED"}];while(state.phase!==phase)state=reducePathA(state,path.shift()!);expect(reducePathA(state,{type:"CANCEL"})).toMatchObject({phase:"cancelled",cleanup_required:true});});
 it("expires rooms and retries failures without carrying room authority",()=>{const waiting=advance([{type:"START"},{type:"ROOM_CREATED",room}]);expect(reducePathA(waiting,{type:"EXPIRE"}).phase).toBe("expired");const failed=reducePathA(waiting,{type:"FAIL",error:"network"});expect(reducePathA(failed,{type:"RETRY"})).toEqual({phase:"starting",attempt:2,cleanup_required:false});});
 it("rejects skipped repeated and post-terminal transitions",()=>{expect(()=>reducePathA(initialPathAState(),{type:"PROFILE_VERIFIED"})).toThrow("illegal");const done=advance([{type:"START"},{type:"ROOM_CREATED",room},{type:"STATUS",status:"awaiting_vps"},{type:"STATUS",status:"completed"},{type:"COMPLETION_VALIDATED"},{type:"CREDENTIAL_PERSISTED"},{type:"PROFILE_VERIFIED"}]);expect(()=>reducePathA(done,{type:"RETRY"})).toThrow("illegal");});
});
