export type DiscoverySource = "loopback" | "bonjour" | "tailscale" | "saved_hint" | "environment" | "manual";
export type PairingRoomStatus = "created" | "awaiting_operator" | "awaiting_vps" | "completed" | "expired" | "revoked" | "failed";
export type ReconciliationRelation = "same_project_separate_authority" | "preferred_profile" | "mirror_read_only" | "not_same_project";

export interface FocusaDaemonCandidateV1 { schema: "focusa.daemon_candidate.v1"; candidate_id: string; base_url: string; source: DiscoverySource; location: "local" | "remote"; observed_at: string; health_status: "healthy" | "unavailable"; latency_ms: number; daemon_id?: string; machine_id?: string; version?: string; capabilities?: string[]; }
export interface FocusaPlatformHintV1 { schema: "focusa.platform_hint.v1"; daemon_url: string; daemon_id?: string; device_id?: string; paired: boolean; client_types_seen: string[]; last_verified_at: string; }
export interface CockpitPairingRoomV1 { schema: "focusa.cockpit_pairing_room.v1"; room_id: string; nonce: string; client_type: "cockpit"; daemon_url: string; status: PairingRoomStatus; created_at: string; expires_at: string; bridge_owner: "cockpit" | "menubar" | "none"; pair_url?: string; pair_code?: string; menubar_device_id?: string; }
export interface AuthenticatedDaemonProfileV1 { schema: "focusa.authenticated_daemon_profile.v1"; profile_id: string; daemon_id: string; daemon_url: string; device_id: string; client_type: "cockpit"; token_handle: string; scopes: string[]; source: "fresh_pairing" | "auto_via_menubar" | "imported"; paired_at: string; expires_at: string; last_verified_at: string; status: "active" | "unavailable" | "expired" | "revoked" | "conflict"; }
export interface DaemonProjectCandidateV1 { schema: "focusa.daemon_project_candidate.v1"; daemon_id: string; profile_id: string; project_root: string; project_id: string; canonical_name: string; identity_status: "verified" | "unverified" | "conflict"; observed_at: string; repo_remote?: string; continuities?: string[]; }
export interface ProjectScopeBindingV1 { schema: "focusa.project_scope_binding.v1"; binding_id: string; daemon_id: string; profile_id: string; project_id: string; project_root: string; continuity_id: string; authority_status: "verified" | "read_only" | "conflict"; selected_at: string; workpoint_id?: string; }
export interface ScopeReconciliationDecisionV1 { schema: "focusa.scope_reconciliation_decision.v1"; decision_id: string; left_binding_id: string; right_binding_id: string; relation: ReconciliationRelation; operator_confirmed: true; created_at: string; evidence_refs: string[]; }

const opaque = /^[A-Za-z0-9._~:-]{1,256}$/;
const forbidden = /token|secret|password|authorization|private.?key/i;
function object(value: unknown, label: string): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${label} must be an object`); return value as Record<string, unknown>; }
function exact(item: Record<string, unknown>, allowed: string[], label: string) { for (const key of Object.keys(item)) { if (!allowed.includes(key)) throw new Error(`${label} contains unknown field ${key}`); } }
function text(item: Record<string, unknown>, key: string, label: string): string { const value = item[key]; if (typeof value !== "string" || !value) throw new Error(`${label}.${key} is required`); return value; }
function ref(item: Record<string, unknown>, key: string, label: string): string { const value = text(item, key, label); if (!opaque.test(value)) throw new Error(`${label}.${key} is not opaque`); return value; }
function timestamp(item: Record<string, unknown>, key: string, label: string): string { const value = text(item, key, label); if (!Number.isFinite(Date.parse(value))) throw new Error(`${label}.${key} is not a timestamp`); return value; }
function url(item: Record<string, unknown>, key: string, label: string): string { const value = text(item, key, label); const parsed = new URL(value); if (!/^https?:$/.test(parsed.protocol) || parsed.username || parsed.password || parsed.hash) throw new Error(`${label}.${key} is not an allowed URL`); return value.replace(/\/$/, ""); }
function strings(value: unknown, label: string): string[] { if (!Array.isArray(value) || value.some((entry) => typeof entry !== "string" || !entry || entry.length > 256)) throw new Error(`${label} must be bounded strings`); return [...new Set(value)]; }
function optionalRef(item: Record<string, unknown>, key: string, label: string): string | undefined { return item[key] === undefined ? undefined : ref(item, key, label); }
function rejectSecretShape(item: Record<string, unknown>, label: string) { for (const key of Object.keys(item)) if (forbidden.test(key)) throw new Error(`${label} contains forbidden secret field`); }

export function parseFocusaDaemonCandidate(value: unknown): FocusaDaemonCandidateV1 {
  const x=object(value,"candidate"); exact(x,["schema","candidate_id","base_url","source","location","observed_at","health_status","latency_ms","daemon_id","machine_id","version","capabilities"],"candidate"); if(x.schema!=="focusa.daemon_candidate.v1") throw new Error("candidate schema mismatch");
  const source=text(x,"source","candidate") as DiscoverySource; if(!["loopback","bonjour","tailscale","saved_hint","environment","manual"].includes(source)) throw new Error("candidate source unsupported");
  const location=text(x,"location","candidate") as "local"|"remote"; if(!["local","remote"].includes(location)) throw new Error("candidate location unsupported"); const health_status=text(x,"health_status","candidate") as "healthy"|"unavailable"; if(!["healthy","unavailable"].includes(health_status)) throw new Error("candidate health unsupported"); if(typeof x.latency_ms!=="number"||x.latency_ms<0) throw new Error("candidate latency invalid");
  return {schema:"focusa.daemon_candidate.v1",candidate_id:ref(x,"candidate_id","candidate"),base_url:url(x,"base_url","candidate"),source,location,observed_at:timestamp(x,"observed_at","candidate"),health_status,latency_ms:x.latency_ms,daemon_id:optionalRef(x,"daemon_id","candidate"),machine_id:optionalRef(x,"machine_id","candidate"),version:x.version===undefined?undefined:text(x,"version","candidate"),capabilities:x.capabilities===undefined?undefined:strings(x.capabilities,"candidate.capabilities")};
}

export function parseFocusaPlatformHint(value: unknown): FocusaPlatformHintV1 {
  const x=object(value,"hint"); rejectSecretShape(x,"hint"); exact(x,["schema","daemon_url","daemon_id","device_id","paired","client_types_seen","last_verified_at"],"hint"); if(x.schema!=="focusa.platform_hint.v1"||typeof x.paired!=="boolean") throw new Error("hint contract invalid");
  return {schema:"focusa.platform_hint.v1",daemon_url:url(x,"daemon_url","hint"),daemon_id:optionalRef(x,"daemon_id","hint"),device_id:optionalRef(x,"device_id","hint"),paired:x.paired,client_types_seen:strings(x.client_types_seen,"hint.client_types_seen"),last_verified_at:timestamp(x,"last_verified_at","hint")};
}

export function parseCockpitPairingRoom(value: unknown): CockpitPairingRoomV1 {
  const x=object(value,"room"); rejectSecretShape(x,"room"); exact(x,["schema","room_id","nonce","client_type","daemon_url","status","created_at","expires_at","bridge_owner","pair_url","pair_code","menubar_device_id"],"room"); if(x.schema!=="focusa.cockpit_pairing_room.v1"||x.client_type!=="cockpit") throw new Error("room contract invalid"); const status=text(x,"status","room") as PairingRoomStatus; if(!["created","awaiting_operator","awaiting_vps","completed","expired","revoked","failed"].includes(status)) throw new Error("room status unsupported"); const bridge_owner=text(x,"bridge_owner","room") as CockpitPairingRoomV1["bridge_owner"]; if(!["cockpit","menubar","none"].includes(bridge_owner)) throw new Error("bridge owner unsupported");
  return {schema:"focusa.cockpit_pairing_room.v1",room_id:ref(x,"room_id","room"),nonce:ref(x,"nonce","room"),client_type:"cockpit",daemon_url:url(x,"daemon_url","room"),status,created_at:timestamp(x,"created_at","room"),expires_at:timestamp(x,"expires_at","room"),bridge_owner,pair_url:x.pair_url===undefined?undefined:url(x,"pair_url","room"),pair_code:x.pair_code===undefined?undefined:ref(x,"pair_code","room"),menubar_device_id:optionalRef(x,"menubar_device_id","room")};
}

export function parseAuthenticatedDaemonProfile(value: unknown): AuthenticatedDaemonProfileV1 {
  const x=object(value,"profile"); exact(x,["schema","profile_id","daemon_id","daemon_url","device_id","client_type","token_handle","scopes","source","paired_at","expires_at","last_verified_at","status"],"profile"); if(x.schema!=="focusa.authenticated_daemon_profile.v1"||x.client_type!=="cockpit") throw new Error("profile contract invalid"); const source=text(x,"source","profile") as AuthenticatedDaemonProfileV1["source"]; if(!["fresh_pairing","auto_via_menubar","imported"].includes(source)) throw new Error("profile source unsupported"); const status=text(x,"status","profile") as AuthenticatedDaemonProfileV1["status"]; if(!["active","unavailable","expired","revoked","conflict"].includes(status)) throw new Error("profile status unsupported");
  return {schema:"focusa.authenticated_daemon_profile.v1",profile_id:ref(x,"profile_id","profile"),daemon_id:ref(x,"daemon_id","profile"),daemon_url:url(x,"daemon_url","profile"),device_id:ref(x,"device_id","profile"),client_type:"cockpit",token_handle:ref(x,"token_handle","profile"),scopes:strings(x.scopes,"profile.scopes"),source,paired_at:timestamp(x,"paired_at","profile"),expires_at:timestamp(x,"expires_at","profile"),last_verified_at:timestamp(x,"last_verified_at","profile"),status};
}

export function parseDaemonProjectCandidate(value: unknown): DaemonProjectCandidateV1 { const x=object(value,"project"); exact(x,["schema","daemon_id","profile_id","project_root","project_id","canonical_name","identity_status","observed_at","repo_remote","continuities"],"project"); if(x.schema!=="focusa.daemon_project_candidate.v1") throw new Error("project schema mismatch"); const identity_status=text(x,"identity_status","project") as DaemonProjectCandidateV1["identity_status"]; if(!["verified","unverified","conflict"].includes(identity_status)) throw new Error("project identity unsupported"); return {schema:"focusa.daemon_project_candidate.v1",daemon_id:ref(x,"daemon_id","project"),profile_id:ref(x,"profile_id","project"),project_root:text(x,"project_root","project"),project_id:ref(x,"project_id","project"),canonical_name:text(x,"canonical_name","project"),identity_status,observed_at:timestamp(x,"observed_at","project"),repo_remote:x.repo_remote===undefined?undefined:url(x,"repo_remote","project"),continuities:x.continuities===undefined?undefined:strings(x.continuities,"project.continuities")}; }
export function parseProjectScopeBinding(value: unknown): ProjectScopeBindingV1 { const x=object(value,"binding"); exact(x,["schema","binding_id","daemon_id","profile_id","project_id","project_root","continuity_id","authority_status","selected_at","workpoint_id"],"binding"); if(x.schema!=="focusa.project_scope_binding.v1") throw new Error("binding schema mismatch"); const authority_status=text(x,"authority_status","binding") as ProjectScopeBindingV1["authority_status"]; if(!["verified","read_only","conflict"].includes(authority_status)) throw new Error("binding authority unsupported"); return {schema:"focusa.project_scope_binding.v1",binding_id:ref(x,"binding_id","binding"),daemon_id:ref(x,"daemon_id","binding"),profile_id:ref(x,"profile_id","binding"),project_id:ref(x,"project_id","binding"),project_root:text(x,"project_root","binding"),continuity_id:ref(x,"continuity_id","binding"),authority_status,selected_at:timestamp(x,"selected_at","binding"),workpoint_id:optionalRef(x,"workpoint_id","binding")}; }
export function parseScopeReconciliationDecision(value: unknown): ScopeReconciliationDecisionV1 { const x=object(value,"reconciliation"); exact(x,["schema","decision_id","left_binding_id","right_binding_id","relation","operator_confirmed","created_at","evidence_refs"],"reconciliation"); if(x.schema!=="focusa.scope_reconciliation_decision.v1"||x.operator_confirmed!==true) throw new Error("reconciliation requires operator confirmation"); const relation=text(x,"relation","reconciliation") as ReconciliationRelation; if(!["same_project_separate_authority","preferred_profile","mirror_read_only","not_same_project"].includes(relation)) throw new Error("reconciliation relation unsupported"); const left=ref(x,"left_binding_id","reconciliation"), right=ref(x,"right_binding_id","reconciliation"); if(left===right) throw new Error("reconciliation bindings must differ"); return {schema:"focusa.scope_reconciliation_decision.v1",decision_id:ref(x,"decision_id","reconciliation"),left_binding_id:left,right_binding_id:right,relation,operator_confirmed:true,created_at:timestamp(x,"created_at","reconciliation"),evidence_refs:strings(x.evidence_refs,"reconciliation.evidence_refs")}; }
