#!/usr/bin/env node
/**
 * stamp-cockpit-version — sibling of Focusa scripts/stamp-release-version.
 *
 * Writes the current tag-derived version into:
 *   - apps/cockpit/src/lib/version.ts
 *   - apps/cockpit/src-tauri/tauri.conf.json (only updates if mismatched)
 *
 * Usage:
 *   node scripts/stamp-cockpit-version/version.ts <version>
 *
 * Exits 0 on success, non-zero on failure.
 */

import { readFile, writeFile } from "fs/promises";
import { join } from "path";

const ROOT = process.cwd();

function fail(msg) {
  console.error(`stamp-cockpit-version: ${msg}`);
  process.exit(1);
}

async function main() {
  const version = process.argv[2];
  if (!version || !/^\d+\.\d+\.\d+(?:-(?:stable|preview|dev))?$/.test(version)) {
    fail("usage: version.ts <X.Y.Z[-stable|-preview|-dev]>");
  }

  // 1. apps/cockpit/src/lib/version.ts
  const versionTsPath = join(ROOT, "src", "lib", "version.ts");
  const versionTsContent =
`// Generated by scripts/stamp-cockpit-version. Do not edit by hand.
export const APP_VERSION = "${version}";
export const APP_CHANNEL = "${version.includes("-") ? version.split("-")[1] : "stable"}";
`;
  await writeFile(versionTsPath, versionTsContent, "utf8");
  console.log(`wrote ${versionTsPath}`);

  // 2. apps/cockpit/src-tauri/tauri.conf.json
  const tauriConfPath = join(ROOT, "src-tauri", "tauri.conf.json");
  const original = await readFile(tauriConfPath, "utf8");
  const updated = original.replace(/"version": "[^"]+"/, `"version": "${version}"`);
  if (updated === original) {
    console.log(`tauri.conf.json already at ${version}`);
  } else {
    await writeFile(tauriConfPath, updated, "utf8");
    console.log(`updated tauri.conf.json to ${version}`);
  }
}

main().catch((err) => fail(err.stack || err.message));
